[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'jason0x43/vim-js-indent'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'luochen1990/rainbow'
