[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
on_event = 'InsertEnter'
on_ft = ['snippet']

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = 'has("lua")'
on_event = 'InsertEnter'

[[plugins]]
repo = 'tomtom/tcomment_vim'
on_event = 'InsertEnter'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'jwalton512/vim-blade'
on_ft = ['php']
